[package]
name = "bevy-crab-pong"
version = "0.1.0"
authors = ["Joshua Ols <joshua.d.ols@gmail.com>"]
edition = "2021"
rust-version = "1.64"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bevy = { git = 'https://github.com/bevyengine/bevy.git' }
bevy = "0.11.0"
bevy_asset_loader = { version = "0.17.0", features = ["standard_dynamic_assets"] }
rand = { version = "0.8.5", features = ["small_rng"] }
ron = "0.8.1"
serde = { version = "1.0.188", features = ["serde_derive"] }
spew = "0.3.0"
