version = "Two"
# tab_spaces = 2
edition="2021"
imports_layout="HorizontalVertical"
imports_granularity="Crate"
group_imports="One"

max_width = 80

format_code_in_doc_comments = true
format_strings = true
wrap_comments = true

use_try_shorthand = true
reorder_impl_items = true

fn_single_line = true
match_block_trailing_comma = true
use_field_init_shorthand = true
